# Builds & uploads a tauri build to the artifact 'tauri-build'
name: Build Tauri Application
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, linux, windows-latest]
    runs-on: ${{ matrix.platform == 'linux' && 'ubuntu-20.04' || matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev libgtk-3-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: pnpm i

      - name: Build the app
        uses: tauri-apps/tauri-action@v0

      - name: Find
        if: matrix.platform != 'windows-latest'
        run: find .
      - name: Tree
        if: matrix.platform == 'windows-latest'
        run: tree /F
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: tauri-build
      #     path: <dir>